# Generated by Django 3.0.6 on 2023-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_product', '0002_auto_20230515_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverymethods',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='designservice',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productimages',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productpriceconfigrations',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariantbase',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariantsku',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierproducts',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='variantsimages',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
