# Generated by Django 3.0.6 on 2023-05-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog_product', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('variant_image', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_product.Products')),
            ],
            options={
                'db_table': 'product_variant',
            },
        ),
        migrations.CreateModel(
            name='VariantAssociatedAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Attributes')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.AttributeValues')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_product.Products')),
            ],
            options={
                'db_table': 'variant_associated_attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('express_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('value_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('standard_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_product.Products')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.ProductVariant')),
            ],
            options={
                'db_table': 'product_variants_price',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Attributes')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.AttributeValues')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_product.Products')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variant.ProductVariant')),
            ],
            options={
                'db_table': 'product_variants_combination',
            },
        ),
    ]
