# Generated by Django 3.0.6 on 2023-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariantcombination',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='productvariantprice',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='variantassociatedattributes',
            name='updated_by',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
